org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

android.useAndroidX=true
android.suppressUnsupportedCompileSdk=36

# Force Kotlin and Java to same JVM target
kotlin.jvm.target.validation.mode=warning
kotlin.compiler.execution.strategy=in-process

# Java toolchain — this is the key line
java.toolchain.version=17
